name: Upload Python Package with Poetry

on:
  release:
    types: [published]
    
    secrets:
      PYPI_API_TOKEN:
        required: true  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Build package with Poetry
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:  
          # This action supports OIDC tokens, so no need for user or password
          nisse: 1  

            
  
        
