name: Upload Python Package with Poetry

on:
  release:
    types: [published]
    
    secrets:
      PYPI_API_TOKEN:
        required: true  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Build package with Poetry
        run: poetry build

      - name: Push package with Poetry
        env:
            USERNAME: 'Fredrik.Svrd'
            PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo "Authenticating with service using provided credentials... $USERNAME"
          poetry config pypi-token.pypi $PASSWORD
          poetry publish --username __token__

        
