name: Upload Python Package with Poetry

on:
  release:
    types: [published]
    
    secrets:
      PYPI_API_TOKEN:
        required: true  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies with Poetry
        run: |
          poetry install
      - name: Build package with Poetry
        run: poetry build

      - name: Push package with Poetry
        env:
            POETRY_HTTP_BASIC_PYPI_USERNAME: 'Fredrik.Svrd'
            POETRY_HTTP_BASIC_PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          echo "Authenticating with service using provided credentials..."
          peotry publish --username $POETRY_HTTP_BASIC_PYPI_USERNAME --password $POETRY_HTTP_BASIC_PYPI_PASSWORD

        
